name: PHPCS

on: [push]

jobs:
  test-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
	- uses: php-actions/composer@v6

    - name: Run PHPCS
      run: vendor/bin/phpcs
