name: PHPCS

on: [push]

jobs:
  test-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We update composer to avoid builds failing because of composer bugs see DWOPS-182
    - name: Update Composer
      run: |
        sudo composer self-update --2
        sudo chown $USER $HOME/.composer

    # This step is only required for plugins/themes that actualy have composer dependencies.
    # That said it's just easier to add this by default for every plugin/theme.
    - name: Configure Composer
      run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

    - name: Install Composer requirements
      run: composer install

    - name: Run PHPCS
      run: vendor/bin/phpcs
