name: PHPUnit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer
      uses: php-actions/composer@v6

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: root
        mysql database: wordpress_test

    - name: Set up WP and its test suite
      run: |
        bash tests/install-wp-tests.sh wordpress_test root root localhost latest true $RUNNER_TEMP
        echo "WP_TESTS_DIR=$(echo $RUNNER_TEMP/wordpress-tests-lib)" >> $GITHUB_ENV
        echo "WP_CORE_DIR=$(echo $RUNNER_TEMP/wordpress)" >> $GITHUB_ENV

    - name: Test WP dirs
      run: |
        echo $WP_TESTS_DIR
        ls -la $WP_TESTS_DIR/includes

    - name: Run PHPUnit
      uses: php-actions/phpunit@v3
      with:
        version: 9
