name: PHPUnit

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer
      uses: php-actions/composer@v6

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: root
        mysql database: wordpress_test

    - name: Runs test setup
      run: |
        bash tests/install-wp-tests.sh wordpress_test root root localhost latest true
        echo $WP_CORE_DIR
        ls -la /tmp/wordpress

    - name: Run PHPUnit
      uses: php-actions/phpunit@v3
      with:
        version: 9
